name       : beets
version    : 1.4.6
release    : 8
source     :
    - https://github.com/beetbox/beets/releases/download/v1.4.6/beets-1.4.6.tar.gz : 62079b2338799a64e7816096c5fae3b8909fb139e4d481ec3255336e67765b50
license    : MIT
component  : multimedia.audio
summary    : Beets is the media library management system for obsessive-compulsive
    music geeks.
description: |
    The purpose of beets is to get your music collection right once and for all. It catalogs your collection, automatically improving its metadata as it goes using the MusicBrainz database. Then it provides a bouquet of tools for manipulating and accessing your music.
    Because beets is designed as a library, it can do almost anything you can imagine for your music collection. Via plugins, beets becomes a panacea:
    -  Fetch or calculate all the metadata you could possibly need: album art, lyrics, genres, tempos, ReplayGain levels, or acoustic fingerprints.
    - Get metadata from MusicBrainz, Discogs, or Beatport. Or guess metadata using songs’ filenames or their acoustic fingerprints.
    - Transcode audio to any format you like.
    - Check your library for duplicate tracks and albums or for albums that are missing tracks.
    - Browse your music library graphically through a Web browser and play it in any browser that supports HTML5 Audio.
    - and lots more.
rundeps    :
    - mutagen
    - python-jellyfish
    - python-munkres
    - python-musicbrainzngs
    - python-six
    - python-unidecode
    - pyyaml
setup      : |
    %python3_setup
install    : |
    %python3_install
    ln -s /usr/bin/beet $installdir/usr/bin/beets
