name       : beets
version    : 1.5.0
release    : 13
source     :
    - https://github.com/beetbox/beets/releases/download/v1.5.0/beets-1.5.0.tar.gz : 887f7bbac0fc14c49469e50d406fd216f914a27acf3818c6503c223f9825342b
homepage   : https://beets.io/
license    : MIT
component  : multimedia.audio
summary    : Beets is the media library management system for obsessive-compulsive music geeks.
description: |
    The purpose of beets is to get your music collection right once and for all. It catalogs your collection, automatically improving its metadata as it goes using the MusicBrainz database. Then it provides a bouquet of tools for manipulating and accessing your music.
    Because beets is designed as a library, it can do almost anything you can imagine for your music collection. Via plugins, beets becomes a panacea:
    -  Fetch or calculate all the metadata you could possibly need: album art, lyrics, genres, tempos, ReplayGain levels, or acoustic fingerprints.
    - Get metadata from MusicBrainz, Discogs, or Beatport. Or guess metadata using songs’ filenames or their acoustic fingerprints.
    - Transcode audio to any format you like.
    - Check your library for duplicate tracks and albums or for albums that are missing tracks.
    - Browse your music library graphically through a Web browser and play it in any browser that supports HTML5 Audio.
    - and lots more.
rundeps    :
    - python-confuse
    - python-jellyfish
    - python-mediafile
    - python-munkres
    - python-musicbrainzngs
    - python-unidecode
setup      : |
    %python3_setup
install    : |
    %python3_install
    ln -s /usr/bin/beet $installdir/usr/bin/beets
