name       : beets
version    : 1.6.0
release    : 15
source     :
    - https://github.com/beetbox/beets/archive/refs/tags/v1.6.0.tar.gz : 10716282cb2c221a8496042639558b7477e634a41211ec29281f3b7d85533bed
homepage   : https://beets.io/
license    : MIT
component  : multimedia.audio
summary    : Beets is the media library management system for obsessive-compulsive music geeks
description: |
    Beets is the media library management system for obsessive music geeks. The purpose of beets is to get your music collection right once and for all. It catalogs your collection, automatically improving its metadata as it goes using the MusicBrainz database. Then it provides a bouquet of tools for manipulating and accessing your music. Because beets is designed as a library, it can do almost anything you can imagine for your music collection.
rundeps    :
    - python-confuse
    - python-jellyfish
    - python-mediafile
    - python-munkres
    - python-musicbrainzngs
    - python-unidecode
build      : |
    %python3_setup
install    : |
    %python3_install
    ln -s /usr/bin/beet $installdir/usr/bin/beets
