name       : beets
version    : 1.4.4
release    : 2
source     :
    - https://github.com/beetbox/beets/releases/download/v1.4.4/beets-1.4.4.tar.gz : 0bc4100e548d8b08cf9b09e163af3e274de2dab92b89af3b099b93749b38abb8
license    : MIT
component  : desktop.multimedia
summary    : Beets is the media library management system for obsessive-compulsive music geeks.
description: |
    The purpose of beets is to get your music collection right once and for all. It catalogs your collection, automatically improving its metadata as it goes using the MusicBrainz database. Then it provides a bouquet of tools for manipulating and accessing your music.
    Because beets is designed as a library, it can do almost anything you can imagine for your music collection. Via plugins, beets becomes a panacea:
    -  Fetch or calculate all the metadata you could possibly need: album art, lyrics, genres, tempos, ReplayGain levels, or acoustic fingerprints.
    - Get metadata from MusicBrainz, Discogs, or Beatport. Or guess metadata using songs’ filenames or their acoustic fingerprints.
    - Transcode audio to any format you like.
    - Check your library for duplicate tracks and albums or for albums that are missing tracks.
    - Browse your music library graphically through a Web browser and play it in any browser that supports HTML5 Audio.
    - and lots more.
rundeps    :
    - python-musicbrainzngs
    - python-jellyfish
    - python-unidecode
    - python-six
    - python-munkres
    - pyyaml
setup      : |
    %python3_setup
install    : |
    %python3_install
